'use strict';

// Echo choosing the operation is the boundary this pipeline moves, so the tests
// are written from the attacker's side of it: the model is treated as something
// that can say anything at all, and the question is what the panel does with it.

const assert = require('assert');
const { paramsOf, describeOperations, catalogueForPrompt, extractProposal, refusalLine, promptRules } = require('./echoProposals');
const { OPERATIONS } = require('./ops/catalogue');

// ── The operation list is generated, so it cannot drift from the catalogue ──
const mailbox = OPERATIONS.find(o => o.id === 'mail.mailbox.create');
const mailboxParams = paramsOf(mailbox);
assert.deepEqual(mailboxParams.required.sort(), ['account', 'domain'],
  'a mailbox needs an address and a domain, and nothing else is demanded of the person');
assert.deepEqual(mailboxParams.optional, ['quotaMb'],
  'the size is optional: it has a default and must not be interrogated for');
assert.deepEqual(mailboxParams.generated, ['password'],
  'the password is generated by the box and is never asked of the person or the model');
assert.deepEqual(mailboxParams.generate, ['password'], 'and the server asks for it by name when it files');
assert.deepEqual(mailboxParams.withheld, [], 'nothing about a mailbox is unobtainable');

// A secret with nowhere to come from makes an operation unofferable, rather than
// something the assistant asks a person to type into a chat window.
const { offerable, isSecret } = require('./echoProposals');
assert.ok(isSecret('password') && isSecret('api_key') && isSecret('privateKey'));
assert.ok(!isSecret('key'), 'an SSH public key is not a secret and only the person has it');
assert.ok(!isSecret('apiKeyLabel'), 'a name that merely contains one is not swept up');
assert.ok(!offerable({ withheld: ['password'] }), 'an operation that must be told a secret is not offered');

const described = describeOperations(OPERATIONS);
assert.equal(described.length, OPERATIONS.length, 'every catalogue operation is offered');
assert.ok(!described.some(o => o.required.includes('password') || o.optional.includes('password')),
  'no operation ever asks the model for a password');

const listed = catalogueForPrompt(OPERATIONS, ['mail.mailbox.create', 'site.create']);
assert.match(listed, /mail\.mailbox\.create \| needs: domain, account \| optional: quotaMb/);
assert.ok(!listed.includes('database.create'), 'an operation this box cannot do is not offered');
assert.ok(!/password/.test(listed), 'the list never mentions a generated secret');

// ── Reading the model's answer ───────────────────────────────────────────────
const filed = extractProposal('Filing that now.\n```jotpanel-proposal\n{"operation":"mail.mailbox.create","input":{"domain":"example.com","account":"sales"}}\n```');
assert.equal(filed.proposal.operation, 'mail.mailbox.create');
assert.deepEqual(filed.proposal.input, { domain: 'example.com', account: 'sales' });
assert.equal(filed.text, 'Filing that now.', 'the block never reaches the person');
assert.ok(!filed.text.includes('jotpanel-proposal'));

const asked = extractProposal('Which domain is that for?');
assert.equal(asked.proposal, null, 'a question files nothing');
assert.equal(asked.malformed, false);
assert.equal(asked.text, 'Which domain is that for?');

const howto = extractProposal('Open Mailboxes, pick the domain, then Create.');
assert.equal(howto.proposal, null, 'an answer about the screens files nothing');

// Rubbish in the block is not a proposal, and the rubbish is not shown either.
for (const bad of ['```jotpanel-proposal\nnot json at all\n```',
                   '```jotpanel-proposal\n{"input":{"domain":"example.com"}}\n```',
                   '```jotpanel-proposal\n{"operation":123}\n```',
                   '```jotpanel-proposal\n["mail.mailbox.create"]\n```']) {
  const out = extractProposal(bad);
  assert.equal(out.proposal, null, `refused: ${bad.slice(0, 40)}`);
  assert.equal(out.malformed, true);
  assert.ok(!out.text.includes('jotpanel-proposal'), 'a broken block is never shown to the person');
}

// An operation the catalogue does not have, or a parameter it does not know, is
// carried no further than this: the server validates both again in propose().
const invented = extractProposal('```jotpanel-proposal\n{"operation":"server.rm -rf","input":{"path":"/"}}\n```');
assert.equal(invented.proposal.operation, 'server.rm -rf',
  'nothing is guessed or corrected here; the catalogue check is the server\'s job');
assert.ok(!OPERATIONS.some(o => o.id === invented.proposal.operation),
  'and the catalogue does not contain it, so propose() refuses it');

// Input must be an object. A list or a string could otherwise reach normalize.
const listInput = extractProposal('```jotpanel-proposal\n{"operation":"mail.mailbox.create","input":["example.com"]}\n```');
assert.deepEqual(listInput.proposal.input, {}, 'a parameter bag that is not an object becomes empty');

// ── What the person is told ──────────────────────────────────────────────────
assert.match(refusalLine('The mail server is not installed yet'),
  /could not put that in Activity: The mail server is not installed yet/);
assert.match(refusalLine(''), /could not put that in Activity\./);

const rules = promptRules(listed);
assert.ok(/Ask one short question for that one thing/.test(rules), 'a missing parameter is asked for, not guessed');
assert.ok(/do not explain the screens/.test(rules), 'a request is not answered with instructions');
assert.ok(/Never put a password or any other secret in the block/.test(rules));
assert.ok(/answer it in plain words with no block/.test(rules), 'a question still gets its how-to answer');

console.log('echo proposal checks passed — generated catalogue, one fenced block, nothing acted on here');

// An optional parameter is never interrogated for, but its default must be on
// the card. A mailbox with no size chosen has no size limit, and a person
// approving one is owed that sentence rather than silence.
{
  const create = OPERATIONS.find(o => o.id === 'mail.mailbox.create');
  assert.match(create.summary({ account: 'info', domain: 'site1.example.com' }), /with no size limit/,
    'the default the person did not choose is stated');
  assert.match(create.summary({ account: 'info', domain: 'site1.example.com', quotaMb: 2048 }), /limited to 2048 MB/,
    'and a size they did choose is stated too');
  console.log('optional-default checks passed — the card says what it will do');
}

// Voice is asked for, never assumed. A panel that downloaded 350 MB of models
// onto somebody else's machine unasked would be doing the thing this product
// exists to refuse.
{
  const voice = OPERATIONS.find(o => o.id === 'stack.install.voice');
  assert.ok(voice, 'installing voice is an operation a person can approve');
  assert.equal(voice.capability, 'stack.install');
  assert.equal(voice.risk, 'elevated', 'it installs packages, so it is not a routine change');
  assert.deepEqual(voice.normalize({ stack: 'anything', packages: ['evil'] }), { stack: 'voice' },
    'the caller cannot choose what gets installed');
  const said = voice.summary();
  assert.match(said, /350 MB/, 'the size is stated before anyone agrees to it');
  assert.match(said, /never sent to another company/, 'and so is where the speech goes');
  assert.ok(!paramsOf(voice).required.length, 'it asks the person for nothing');
  console.log('voice install checks passed — asked for, fixed job, honest about size and privacy');
}
